### ISSUE TITLE
Implement consistent code style and code formatting for py files

### ISSUE THREAD

**Issue by IE-smhi** [baltrad/rave#34]
Improve the maintainability and readability of RAVE project.

Used ruff https://docs.astral.sh/ruff/ a linter with formatting options
Used isort https://pycqa.github.io/isort/ https://pycqa.github.io/isort/docs/configuration/custom_sections_and_ordering.html
isort only used for the grunt work rest is done manually.

```toml

[tool.isort]
multi_line_output = 3
include_trailing_comma = false
line_length = 120
known_third_party = ["SQLAlchemy", "psycopg2", "numpy", "pygrib", "pyinotify"]
known_first_party = ["baltrad", "_rave*" , "_*"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]

src_paths = ["bin", "Lib"]


[tool.ruff]

exclude = [
  "build/",
  "c-examples/",
  "config/",
  "doc/",
  "doxygen/",
  "librave/",
  "modules/",
  "packaging/",
  "templates/",
  "*.c",
  "*.h",
]
line-length = 120
indent-width = 4

target-version = ["py36", "py37", "py38", "py39"]

[tool.ruff.format]
quote-style = "preserve"
indent-style = "space"
skip-magic-trailing-comma = false
docstring-code-format = false
docstring-code-line-length = "dynamic"
```
